In [15]:
from hoomd import *
import numpy

# Setting initial conditions in python

You can set initial conditions for HOOMD using arbitrary python code via a snapshot. Use this to generate random initial conditions within a job script, provide customizable parameters for the initial conditions, or read from a custom file format. For more information, see the [data](http://hoomd-blue.readthedocs.io/en/stable/module-hoomd-data.html) and [init.read_snapshot](http://hoomd-blue.readthedocs.io/en/stable/module-hoomd-init.html#hoomd.init.read_snapshot) documentation.

## Make Snapshot

The first step is to make a snapshot to hold the particles. `N` is the number of particles to create, `box` is the simulation box, and `particle_types` is a list of the particle type names.

In [10]:
context.initialize("")
snap = data.make_snapshot(N=4, box=data.boxdim(L=10), particle_types=['A', 'B'])

The snapshot object contains [numpy](http://www.numpy.org/) arrays with all of the particle properties.

In [11]:
print(snap.particles.position)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [12]:
print(snap.particles.diameter)

[ 1.  1.  1.  1.]


In [13]:
print(snap.particles.velocity)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


As you can see, all particles are initialized with default properties. See [data.make_snapshot](http://hoomd-blue.readthedocs.io/en/stable/module-hoomd-data.html#hoomd.data.make_snapshot) for more information on defaults.

## Populate snapshot

The next step is to populate the snapshot with your desired initial condition. This can be created by any code, or assigned by hand. Make sure to assign positions for all particles. Your simulation will blow up if you start all particles at the origin.

In [14]:
snap.particles.position[0] = [1,2,3]
snap.particles.position[1] = [-1,-2,-3]
snap.particles.position[2] = [3,2,1]
snap.particles.position[3] = [-3,-2,-1]

You must assign elements of the arrays in the snapshot. You can copy an existing numpy array like so:

In [27]:
numpy.random.seed(10)
my_velocity = numpy.random.random((4,3)) * 2 - 1
snap.particles.velocity[:] = my_velocity[:]
print(snap.particles.velocity)

[[ 0.54264128 -0.95849609  0.26729646]
 [ 0.49760777 -0.00298598 -0.55040669]
 [-0.60387427  0.52106142 -0.66177833]
 [-0.82332039  0.37071964  0.90678668]]


We assigned `particle_types=['A', 'B']` above. This makes the type id of 0 identify particle type 'A', and type id 1 identify particle type 'B'. The type id is just the index of the name in the list. Let's make the first three particles 'B' and the last one 'A':

In [28]:
snap.particles.typeid[:] = [1,1,1,0]

## Initialize from snapshot

The snapshot object `snap` stores a self-contained version of the system configuration. It is not connected with the rest of HOOMD. You can store as many snapshot objects as you can fit in memory, all with different properties. Use `init.read_snapshot` to initialize a HOOMD simulation from a snapshot.

In [29]:
init.read_snapshot(snap)

notice(2): Group "all" created containing 4 particles


Now HOOMD is ready for pair forces, integrators, and other commands to configure the simulation run.